websocket:
  port: 8989
  context-path: ${WEBSOCKET_PATH:/chat}

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:127.0.0.1}
    username: ${RABBIT_MQ_USER:open-im}
    password: ${RABBIT_MQ_PASS:open-im}
    port: ${RABBIT_MQ_PORT:5672}